// <auto-generated />
using System;
using Evertorch.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Evertorch.Persistence
{
    [DbContext(typeof(EvertorchDbContext))]
    [Migration("20261003172540_AddTradesAndStorage")]
    partial class AddTradesAndStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evertorch.Persistence.AccountRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LoginNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_normalized");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordScheme")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("password_scheme");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("LoginNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_login_normalized");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_password", "(password_hash IS NULL) = (password_scheme IS NULL)");

                            t.HasCheckConstraint("ck_accounts_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.AccountStorageRow", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("AccountId")
                        .HasName("pk_account_storages");

                    b.ToTable("account_storages", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_storages_revision", "revision BETWEEN 0 AND 4294967295");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterQuestRow", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<string>("QuestDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quest_definition_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "QuestDefinitionId")
                        .HasName("pk_character_quests");

                    b.ToTable("character_quests", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_quests_progress", "progress >= 0");

                            t.HasCheckConstraint("ck_character_quests_state", "state IN ('active', 'completed')");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<int>("Agi")
                        .HasColumnType("integer")
                        .HasColumnName("agi");

                    b.Property<long>("BaseExp")
                        .HasColumnType("bigint")
                        .HasColumnName("base_exp");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer")
                        .HasColumnName("base_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Currency")
                        .HasColumnType("bigint")
                        .HasColumnName("currency");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("dex");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<long>("InventoryRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_revision");

                    b.Property<string>("JobDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_definition_id");

                    b.Property<long>("JobExp")
                        .HasColumnType("bigint")
                        .HasColumnName("job_exp");

                    b.Property<int>("JobLevel")
                        .HasColumnType("integer")
                        .HasColumnName("job_level");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Luk")
                        .HasColumnType("integer")
                        .HasColumnName("luk");

                    b.Property<string>("MapDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_definition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("character varying(23)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(23)
                        .HasColumnType("character varying(23)")
                        .HasColumnName("name_normalized");

                    b.Property<float>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real")
                        .HasColumnName("position_z");

                    b.Property<int>("Sp")
                        .HasColumnType("integer")
                        .HasColumnName("sp");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("str");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("Vit")
                        .HasColumnType("integer")
                        .HasColumnName("vit");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_name_normalized");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_experience", "base_exp >= 0 AND job_exp >= 0");

                            t.HasCheckConstraint("ck_characters_inventory_revision", "inventory_revision BETWEEN 0 AND 4294967295");

                            t.HasCheckConstraint("ck_characters_levels", "base_level >= 1 AND job_level >= 1");

                            t.HasCheckConstraint("ck_characters_name", "name ~ '^[A-Za-z0-9]{4,23}$' AND name_normalized = lower(name)");

                            t.HasCheckConstraint("ck_characters_resources", "hp >= 0 AND sp >= 0 AND currency BETWEEN 0 AND 1000000000");

                            t.HasCheckConstraint("ck_characters_stats", "str >= 0 AND agi >= 0 AND vit >= 0 AND int >= 0 AND dex >= 0 AND luk >= 0");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterSkillRow", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<string>("SkillDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skill_definition_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("CharacterId", "SkillDefinitionId")
                        .HasName("pk_character_skills");

                    b.ToTable("character_skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_skills_level", "level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.EquipmentRow", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<string>("Slot")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("slot");

                    b.Property<long>("InventoryItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_item_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "Slot")
                        .HasName("pk_equipment");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_equipment_inventory_item_id");

                    b.HasIndex("CharacterId", "InventoryItemId")
                        .HasDatabaseName("ix_equipment_character_id_inventory_item_id");

                    b.ToTable("equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_slot", "slot IN ('Weapon', 'Armor')");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.InventoryItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<string>("InstanceDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("instance_data_json");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_definition_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RefineLevel")
                        .HasColumnType("integer")
                        .HasColumnName("refine_level");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasAlternateKey("CharacterId", "Id")
                        .HasName("ak_inventory_items_character_id_id");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_quantity", "quantity BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_inventory_items_refine_level", "refine_level >= 0");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.LedgerRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrencyDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("currency_delta");

                    b.Property<string>("ItemDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_definition_id");

                    b.Property<long?>("ItemInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_instance_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_type");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.HasKey("Id")
                        .HasName("pk_economy_ledger");

                    b.HasIndex("ActorCharacterId")
                        .HasDatabaseName("ix_economy_ledger_actor_character_id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_economy_ledger_operation_id");

                    b.ToTable("economy_ledger", null, t =>
                        {
                            t.HasCheckConstraint("ck_economy_ledger_operation_type", "operation_type IN ('pickup', 'equip', 'unequip', 'consume', 'buy', 'sell', 'quest_reward', 'boss_reward', 'trade', 'storage_deposit', 'storage_withdraw')");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.PartyMemberRow", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("integer")
                        .HasColumnName("join_order");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id");

                    b.HasKey("CharacterId")
                        .HasName("pk_party_members");

                    b.HasIndex("PartyId", "CharacterId")
                        .IsUnique()
                        .HasDatabaseName("ux_party_members_party_id_character_id");

                    b.ToTable("party_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_party_members_join_order", "join_order >= 1");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.PartyRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LeaderCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("leader_character_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("Evertorch.Persistence.SessionTokenRow", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.HasKey("TokenHash")
                        .HasName("pk_session_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_session_tokens_account_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_session_tokens_expires_at");

                    b.ToTable("session_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_tokens_expiry", "expires_at > issued_at");

                            t.HasCheckConstraint("ck_session_tokens_token_hash", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.StorageItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("InstanceDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("instance_data_json");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_definition_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RefineLevel")
                        .HasColumnType("integer")
                        .HasColumnName("refine_level");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_storage_items");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_storage_items_account_id");

                    b.ToTable("storage_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_storage_items_quantity", "quantity BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("ck_storage_items_refine_level", "refine_level >= 0");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.TradeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<long>("FirstCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_character_id");

                    b.Property<long>("SecondCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("second_character_id");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("FirstCharacterId")
                        .HasDatabaseName("ix_trades_first_character_id");

                    b.HasIndex("SecondCharacterId")
                        .HasDatabaseName("ix_trades_second_character_id");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("ck_trades_characters", "first_character_id < second_character_id");
                        });
                });

            modelBuilder.Entity("Evertorch.Persistence.AccountStorageRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_storages_accounts");
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterQuestRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_quests_characters");
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts");
                });

            modelBuilder.Entity("Evertorch.Persistence.CharacterSkillRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_skills_characters");
                });

            modelBuilder.Entity("Evertorch.Persistence.EquipmentRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_characters");

                    b.HasOne("Evertorch.Persistence.InventoryItemRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId", "InventoryItemId")
                        .HasPrincipalKey("CharacterId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_owned_inventory_item");
                });

            modelBuilder.Entity("Evertorch.Persistence.InventoryItemRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_characters");
                });

            modelBuilder.Entity("Evertorch.Persistence.LedgerRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("ActorCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_economy_ledger_characters");
                });

            modelBuilder.Entity("Evertorch.Persistence.PartyMemberRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_members_characters");

                    b.HasOne("Evertorch.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_members_parties");
                });

            modelBuilder.Entity("Evertorch.Persistence.SessionTokenRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_tokens_accounts");
                });

            modelBuilder.Entity("Evertorch.Persistence.StorageItemRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.AccountStorageRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_storage_items_account_storages");
                });

            modelBuilder.Entity("Evertorch.Persistence.TradeRow", b =>
                {
                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("FirstCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_first_character");

                    b.HasOne("Evertorch.Persistence.CharacterRow", null)
                        .WithMany()
                        .HasForeignKey("SecondCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_second_character");
                });
#pragma warning restore 612, 618
        }
    }
}
